// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/asteroid-shiba/PresalePage.tsx": () => import("../components/mockups/asteroid-shiba/PresalePage.tsx"),
  "./components/mockups/token-card/TokenCard.tsx": () => import("../components/mockups/token-card/TokenCard.tsx"),
  "./components/mockups/aethpad-home/Home.tsx": () => import("../components/mockups/aethpad-home/Home.tsx")
};
